### ISSUE TITLE
Error: 'curl_noise' is not an exported object from 'namespace:ambient'

### ISSUE THREAD

**Issue by SaranjeetKaur** [thomasp85/thomasp85.github.io#1]
I am using these packages:

`# install.packages("remotes")`
`remotes::install_github("djnavarro/rosemary")`
`remotes::install_github("djnavarro/jasmines")`

However, when I execute the following:
`library(jasmines)`
`library(rosemary)`
`options(rosemary.images = "/cloud/project")`
`rosemary::heart_sketch()`

This error crops:

_Error: 'curl_noise' is not an exported object from 'namespace:ambient'_

**Comment by thomasp85** [comment]
I’m afraid I don’t see what this has to do with my old blog source code?

**Comment by SaranjeetKaur** [comment]
I am really sorry, I opened this issue in the wrong place. My bad!
